
services:

  # stream:
  #   # image: cgvalle/ciervo_stream:latest
  #   restart: always
  #   pull_policy: always
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile.cyton
  #   depends_on:
  #   - nanomq

