
services:
  nanomq:
    image: emqx/nanomq:latest
    ports:
      - "1883:1883"
      - "8083:8083"
    environment:
      - EMQX_NAME=nanomq
      - EMQX_LISTENER__TCP__EXTERNAL=1883
      - EMQX_LISTENER__WS__EXTERNAL=8083
      - EMQX_ALLOW_ANONYMOUS=true
      - NANOMQ_NUM_TASKQ_THREAD=4
      - NANOMQ_NUM_WORKER_THREAD=4
    restart: always 

  stream:
    # image: cgvalle/ciervo_stream:latest
    restart: always
    privileged: true
    pull_policy: always
    volumes:
      - /dev:/dev
    build:
      context: .
      dockerfile: docker/Dockerfile.cyton
    depends_on:
    - nanomq

  # inference:
  #  # image: cgvalle/ciervo_inference:latest
  #  restart: always
  #  privileged: true   
  #  pull_policy: always
  #  volumes:
  #   - /dev:/dev
  #  build:
  #    context: .
  #    dockerfile: docker/Dockerfile.inference
  #  #depends_on:
  #  #- stream

