
services:

  stream:
    # image: cgvalle/ciervo_stream:latest
    restart: always
    pull_policy: always
    build:
      context: .
      dockerfile: docker/Dockerfile.stream
    depends_on:
      - nanomq

#   influxdb:
#     image: influxdb:latest
#     container_name: influxdb
#     ports:
#       - "8086:8086"
#     environment:
#       - DOCKER_INFLUXDB_INIT_MODE=setup
#       - DOCKER_INFLUXDB_INIT_USERNAME=Hellonston
#       - DOCKER_INFLUXDB_INIT_PASSWORD=Cierv@12345
#       - DOCKER_INFLUXDB_INIT_ORG=Ciervo
#       - DOCKER_INFLUXDB_INIT_BUCKET=Ciervo
#       - DOCKER_INFLUXDB_INIT_RETENTION=1w
#       - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=holas
      
#     volumes:
#       - influxdb-data:/var/lib/influxdb
#   data_collector:
#     build:
#       context: .
#       dockerfile: docker/Dockerfile.getData
#     container_name: data_collector
#     environment:
#       - DOCKER_INFLUXDB_INIT_ORG=Ciervo
#       - DOCKER_INFLUXDB_INIT_BUCKET=Ciervo
#       - DOCKER_INFLUXDB_INIT_RETENTION=1w
#       - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=holas
#     depends_on:
#       - stream
#       - influxdb
#     command: python3 /app/ciervo/saveData/getDataFromRaspberry.py
# volumes:
#   influxdb-data:
